name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Run tests
        run: mvn -q -B clean test
      - name: Upload Extent Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: extent-report
          path: reports/extent-report.html
      - name: Upload Surefire Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: surefire-reports
          path: target/surefire-reports/**
      - name: Upload Artifacts (DB/ETL)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: artifacts
          path: artifacts/**
